version: 2 # The 'version' needs to be case sensitive

sources:
  - name: raw # This is the alias we are giving
    schema: gz_raw_data # This is our dataset

    # Start of sales table
    tables:
      - name: sales # This is the table alias name we are going to use
        identifier: raw_gz_sales # This is the actual table name
        description: sales of Greenweez / we have on row per product_id found in each orders_id

        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        
        freshness:
          warn_after:
            count: 90
            period: day

        # Start of sales columns
        columns:
          - name: date_date
            description: "The date of the transaction."

          - name: orders_id
            description: "The unique identifier for each order."

          - name: products_id
            description: "The unique identifier for each product."

          - name: revenue
            description: "The total revenue generated from the transaction."

          - name: quantity
            description: "The number of items sold in the transaction."
        # End of sales columns
    # End of sales table

    # Start of product table
      - name: product
        identifier: raw_gz_product
        description: "This table contains raw product data."

        # Start of product columns
        columns:
          - name: products_id
            description: "The unique identifier for each product."
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: "The purchase price of the product, cast to a FLOAT64 data type for precision"
        # End of product columns
    # End of product table

    # Start of ship table
      - name: ship
        identifier: raw_gz_ship
        description: "This table contains raw shipping data."

        # Start of ship columns
        columns:
          - name: orders_id
            description: "The unique identifier for each order."
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: "The fee charged for shipping the order."

          - name: logcost
            description: "The logistical cost associated with shipping the order."

          - name: ship_cost
            description: "The total shipping cost, cast to a FLOAT64 data type for precision."
        # End of ship columns
    # End of ship table

